
# vivado_run.tcl -- autogenerated
set proj_name {openMSP430_fpga}
set part_name {xc7a200tfbg676-2}
#file mkdir $proj_name
#cd $proj_name

# create project (force overwrite)
create_project $proj_name . -part $part_name -force

# Set Verilog include directories for `\`include` resolution in synthesis
# Adjust/add paths if your project layout differs.
set inc_dirs [list  "../../../rtl/verilog" "../../../rtl/verilog/openmsp430" "../../../rtl/verilog/openmsp430/periph" ]
# Apply to the default sources fileset
set_property include_dirs $inc_dirs [get_filesets sources_1]

# Parse the legacy ISE .prj if present to add source files (prj file lines assumed relative)
set prjfile {../scripts/openMSP430_fpga.prj}
if {[file exists $prjfile]} {
    set fh [open $prjfile r]
    while {[gets $fh line] >= 0} {
        set line [string trim $line]
        if {$line eq "" || [string index $line 0] == "#" || [string range $line 0 1] == "//"} continue
        # add file (path relative to WORK)
        if {[file exists $line]} {
            add_files -norecurse $line
            puts "INFO: add file: $line"   
        } else {            
            puts "WARNING: listed file not found: $line"            
        }
    }
    close $fh
} else {
    puts "No ../scripts/openMSP430_fpga.prj found — you should add sources manually or update this script."
}

# Also try to add typical RTL folders (adjust if your layout differs)
#if {[file exists "../../rtl/verilog"]} {
#    add_files -norecurse ../../rtl/verilog/**/*
#}

# Add constraints (UCF added as-is; recommend converting to XDC: .xdc)
if {[file exists "../scripts/openMSP430_fpga.xdc"]} {
    add_files -fileset constrs_1 ../scripts/openMSP430_fpga.xdc
} else {
    puts "No constraint file found in ../scripts/"
}

# Update compile order and set top if module exists
update_compile_order -fileset sources_1

# If top module name known, set it (modify if different)
if {[catch {set_property top openMSP430_fpga [get_filesets sources_1]}]} {
    puts "Warning: could not set top to 'openMSP430_fpga' automatically."
}

# Run synthesis
launch_runs synth_1 -jobs 4
wait_on_run synth_1

# Run implementation
launch_runs impl_1 -to_step write_bitstream -jobs 4
wait_on_run impl_1

# Write bitstream (force overwrite)
write_bitstream -force ${proj_name}.bit

# close project
close_project -save
